services:
  api:
    build: backend/
    depends_on:
      - postgres
    
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
  
  postgres:
    image: postgres
    environment:
       - POSTGRES_USER=jdeeza
       - POSTGRES_PASSWORD=password123
       - POSTGRES_DB=lost_and_found
    volumes:
      - postgres-db:/var/lib/postgresql
    ports:
      - "5432:5432"

      # add your DB/env vars here
volumes:
  postgres-db: